CUDA_VISIBLE_DEVICES=0 python main.py --mode fine --epochs 100 --batch 128 --quant_base hawq --arch alexnet --dataset cifar10 --lr 0.001 --act-range-momentum 0.99 --wd 1e-4 --fix-BN --pretrained --channel-wise true --quant-scheme uniform4 --cluster 4 --repr_method max --sub_cluster 8 --nnac true --similarity_method 0.7 --data cifar10 --batch-size 128 --transfer_param --dnn_path pretrained_models/cifar10/alexnet/checkpoint.pth --gpu 0
CUDA_VISIBLE_DEVICES=0 python main.py --mode fine --epochs 100 --batch 128 --quant_base hawq --arch alexnet --dataset cifar100 --lr 0.001 --act-range-momentum 0.99 --wd 1e-4 --fix-BN --pretrained --channel-wise true --quant-scheme uniform4 --cluster 4 --repr_method max --sub_cluster 8 --nnac true --similarity_method 0.7 --data cifar100 --batch-size 128 --transfer_param --dnn_path pretrained_models/cifar100/alexnet/checkpoint.pth --gpu 0
CUDA_VISIBLE_DEVICES=0 python main.py --mode fine --epochs 100 --batch 128 --quant_base hawq --arch alexnet --dataset svhn --lr 0.001 --act-range-momentum 0.99 --wd 1e-4 --fix-BN --pretrained --channel-wise true --quant-scheme uniform4 --cluster 4 --repr_method max --sub_cluster 8 --nnac true --similarity_method 0.7 --data svhn --batch-size 128 --transfer_param --dnn_path pretrained_models/svhn/alexnet/checkpoint.pth --gpu 0

CUDA_VISIBLE_DEVICES=0 python main.py --mode fine --epochs 100 --batch 128 --quant_base hawq --arch resnet20 --dataset cifar10 --lr 0.001 --act-range-momentum 0.99 --wd 1e-4 --fix-BN --pretrained --channel-wise true --quant-scheme uniform4 --cluster 4 --repr_method max --sub_cluster 8 --nnac true --similarity_method 0.7 --data cifar10 --batch-size 128 --gpu 0
CUDA_VISIBLE_DEVICES=0 python main.py --mode fine --epochs 100 --batch 128 --quant_base hawq --arch resnet20 --dataset cifar100 --lr 0.001 --act-range-momentum 0.99 --wd 1e-4 --fix-BN --pretrained --channel-wise true --quant-scheme uniform4 --cluster 4 --repr_method max --sub_cluster 8 --nnac true --similarity_method 0.7 --data cifar100 --batch-size 128 --gpu 0
CUDA_VISIBLE_DEVICES=0 python main.py --mode fine --epochs 100 --batch 128 --quant_base hawq --arch resnet20 --dataset svhn --lr 0.001 --act-range-momentum 0.99 --wd 1e-4 --fix-BN --pretrained --channel-wise true --quant-scheme uniform4 --cluster 4 --repr_method max --sub_cluster 8 --nnac true --similarity_method 0.7 --data svhn --batch-size 128 --gpu 0

CUDA_VISIBLE_DEVICES=0 python main.py --mode fine --epochs 100 --batch 128 --quant_base hawq --arch alexnet --dataset cifar10 --lr 0.001 --act-range-momentum 0.99 --wd 1e-4 --fix-BN --pretrained --channel-wise true --quant-scheme uniform4 --cluster 4 --repr_method max --sub_cluster 8 --nnac true --similarity_method 0.7 --data cifar10 --batch-size 128 --transfer_param --dnn_path pretrained_models/cifar10/alexnet/checkpoint.pth --gpu 0
CUDA_VISIBLE_DEVICES=0 python main.py --mode fine --epochs 100 --batch 128 --quant_base hawq --arch alexnet --dataset cifar100 --lr 0.001 --act-range-momentum 0.99 --wd 1e-4 --fix-BN --pretrained --channel-wise true --quant-scheme uniform4 --cluster 4 --repr_method max --sub_cluster 8 --nnac true --similarity_method 0.7 --data cifar100 --batch-size 128 --transfer_param --dnn_path pretrained_models/cifar100/alexnet/checkpoint.pth --gpu 0
CUDA_VISIBLE_DEVICES=0 python main.py --mode fine --epochs 100 --batch 128 --quant_base hawq --arch alexnet --dataset svhn --lr 0.001 --act-range-momentum 0.99 --wd 1e-4 --fix-BN --pretrained --channel-wise true --quant-scheme uniform4 --cluster 4 --repr_method max --sub_cluster 8 --nnac true --similarity_method 0.7 --data svhn --batch-size 128 --transfer_param --dnn_path pretrained_models/svhn/alexnet/checkpoint.pth --gpu 0

CUDA_VISIBLE_DEVICES=0 python main.py --mode fine --epochs 100 --batch 128 --quant_base hawq --arch resnet20 --dataset cifar10 --lr 0.001 --act-range-momentum 0.99 --wd 1e-4 --fix-BN --pretrained --channel-wise true --quant-scheme uniform4 --cluster 4 --repr_method max --sub_cluster 8 --nnac true --similarity_method 0.7 --data cifar10 --batch-size 128 --gpu 0
CUDA_VISIBLE_DEVICES=0 python main.py --mode fine --epochs 100 --batch 128 --quant_base hawq --arch resnet20 --dataset cifar100 --lr 0.001 --act-range-momentum 0.99 --wd 1e-4 --fix-BN --pretrained --channel-wise true --quant-scheme uniform4 --cluster 4 --repr_method max --sub_cluster 8 --nnac true --similarity_method 0.7 --data cifar100 --batch-size 128 --gpu 0
CUDA_VISIBLE_DEVICES=0 python main.py --mode fine --epochs 100 --batch 128 --quant_base hawq --arch resnet20 --dataset svhn --lr 0.001 --act-range-momentum 0.99 --wd 1e-4 --fix-BN --pretrained --channel-wise true --quant-scheme uniform4 --cluster 4 --repr_method max --sub_cluster 8 --nnac true --similarity_method 0.7 --data svhn --batch-size 128 --gpu 0
